services:
  chatgpt-accesstoken:
    container_name: chatgpt-accesstoken
    image: askaigo/chatgpt-accesstoken:v0.0.0-dd8ee3b
    ports:
      - 8080:8080
    environment:
      - GO_CHATGPT_API_PROXY=http://word:hello@202.182.88.20:17586
    restart: unless-stopped

