services:
  chatgpt-accesstoken:
    container_name: chatgpt-accesstoken
    image: askaigo/chatgpt-accesstoken:latest
    ports:
      - 8080:8080
    environment:
      - PROXY_FILENAME=/root/proxy.txt
    volumes:
      - ./proxy.txt:/root/proxy.txt
    restart: unless-stopped

